{{- $global := .Values.global | default dict }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
spec:
  template:
    spec:
      {{- if $global.k0sURL }}
      downloadURL: "{{ $global.k0sURL }}/k0s-{{ .Values.k0s.version }}-{{ .Values.k0s.arch }}"
      {{- end }}
      version: {{ .Values.k0s.version }}
      {{- with .Values.k0s.workerArgs }}
      args: {{ toYaml . | nindent 8 }}
      {{- end }}
      files:
        - path: /home/{{ .Values.worker.ssh.user }}/.ssh/authorized_keys
          permissions: "0600"
          content: "{{ trim .Values.worker.ssh.publicKey }}"
        {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
        {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
        {{- range $path, $secret := $certs }}
        {{- if $secret }}
        - contentFrom:
            secretRef:
              name: {{ $secret }}
              key: ca.crt
          permissions: "0664"
          path: /usr/local/share/ca-certificates/{{ $path }}
        {{- end }}
        {{- end }}
        {{- end }}
      preStartCommands:
        - chown {{ .Values.worker.ssh.user }} /home/{{ .Values.worker.ssh.user }}/.ssh/authorized_keys
        {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
        - "sudo update-ca-certificates"
        {{- end }}
