apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.name" . }}
  annotations:
    machineset.cluster.x-k8s.io/skip-preflight-checks: "ControlPlaneIsStable"
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.workersNumber }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
    spec:
      version: {{ .Values.kubernetes.version }}
      clusterName: {{ include "cluster.name" . }}
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: EKSConfigTemplate
          name: {{ include "eksconfigtemplate.name" . }}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: AWSMachineTemplate
        name: {{ include "awsmachinetemplate.worker.name" . }}
