configSecret: # @schema type: object; description: Configuration for the Secret that provides controller configuration variables
  create: true # @schema type: boolean; description: Specifies whether the configuration Secret should be created by this chart
  name: "vsphere-variables" # @schema type: string; description: Name of the configuration Secret
  namespace: "" # @schema type: string; description: Namespace of the configuration Secret

config: # @schema type: object; description: Key-value configuration data stored in the configuration Secret. Only used when configSecret.create is true
  VSPHERE_USERNAME: ""
  VSPHERE_PASSWORD: ""
  KUBERNETES_VERSION: ""
  VSPHERE_SERVER: ""
  VSPHERE_DATACENTER: ""
  VSPHERE_DATASTORE: ""
  VSPHERE_NETWORK: ""
  VSPHERE_RESOURCE_POOL: ""
  VSPHERE_FOLDER: ""
  VSPHERE_TEMPLATE: ""
  CONTROL_PLANE_ENDPOINT_IP: ""
  VSPHERE_TLS_THUMBPRINT: ""
  EXP_CLUSTER_RESOURCE_SET: ""
  VSPHERE_SSH_AUTHORIZED_KEY: ""
  VSPHERE_STORAGE_POLICY: ""
  CPI_IMAGE_K8S_VERSION: ""

manager: {} # @schema type: object; description: Controller manager settings, such as feature gates, verbosity and other options

deployment: {} # @schema type: object; description: Deployment-level overrides for the provider controller, including replicas, containers, and scheduling settings

proxy: # @schema type: object; description: Proxy settings of the controller; additionalProperties: false
  enabled: true # @schema type: boolean; description: Enable proxy
