# Cluster parameters
controlPlaneNumber: 3
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"

clusterLabels: {}
clusterAnnotations: {}

# Azure cluster parameters
location: ""
subscriptionID: ""
bastion:
  enabled: false
  bastionSpec:
    azureBastion: {}
clusterIdentity:
  name: ""
  namespace: kcm-system
# Azure machines parameters
controlPlane:
  sshPublicKey: ""
  vmSize: ""
  rootVolumeSize: 30
  image:
    id: ""
    computeGallery: {}
    marketplace:
      publisher: "cncf-upstream"
      offer: "capi"
      sku: "ubuntu-2204-gen1"
      version: "130.3.20240717"

worker:
  sshPublicKey: ""
  vmSize: ""
  rootVolumeSize: 30
  image:
    id: ""
    computeGallery: {}
    marketplace:
      publisher: "cncf-upstream"
      offer: "capi"
      sku: "ubuntu-2204-gen1"
      version: "130.3.20240717"

# K0s parameters
k0s: # @schema description: K0s parameters; type: object
  version: v1.32.6+k0s.0 # @schema description: K0s version; type: string
  arch: amd64 # @schema description: K0s Download URL Arch; type: string; enum: amd64, arm64, arm; default: amd64
  cpArgs: [] # @schema description: Args specifies extra arguments to be passed to k0s controller. See: https://docs.k0sproject.io/stable/cli/k0s_controller/; type: array; item: string; uniqueItems: true
  workerArgs: [] # @schema description: Args specifies extra arguments to be passed to k0s worker. See: https://docs.k0sproject.io/stable/worker-node-config/ See: https://docs.k0sproject.io/stable/cli/k0s_worker/; type: array; item: string; uniqueItems: true
  api: # @schema description: Kubernetes API server parameters; type: object
    extraArgs: {} # @schema description: Map of key-values (strings) for any extra arguments to pass down to Kubernetes api-server process; type: object; additionalProperties: true
  network: # @schema description: Kubernetes cluster network configuration; type: object
    provider: calico # @schema description: Network provider to use (e.g., calico, cilium, flannel, kube-router); type: string
    calico: # @schema description: Calico-specific configuration; type: object
      mode: vxlan # @schema description: Calico network mode (ipip, vxlan, never); type: string
