apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-cm-viewer-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-editor: "true"
    k0rdent.mirantis.com/aggregate-to-namespace-viewer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
