apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kcm.fullname" . }}-controller-manager
  labels:
    control-plane: {{ include "kcm.fullname" . }}-controller-manager
  {{- include "kcm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: {{ include "kcm.fullname" . }}-controller-manager
    {{- include "kcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: {{ include "kcm.fullname" . }}-controller-manager
      {{- include "kcm.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --templates-repo-url={{ .Values.controller.templatesRepoURL }}
        - --global-registry={{ .Values.controller.globalRegistry }}
        - --global-k0s-url={{ .Values.controller.globalK0sURL }}
        - --insecure-registry={{ .Values.controller.insecureRegistry }}
        {{- if .Values.controller.registryCredsSecret }}
        - --registry-creds-secret={{ .Values.controller.registryCredsSecret }}
        {{- end }}
        {{- if .Values.controller.k0sURLCertSecret }}
        - --k0s-url-cert-secret-name={{ .Values.controller.k0sURLCertSecret }}
        {{- end }}
        {{- if .Values.controller.registryCertSecret }}
        - --registry-cert-secret-name={{ .Values.controller.registryCertSecret }}
        {{- end }}
        - --create-management={{ .Values.controller.createManagement }}
        - --create-access-management={{ .Values.controller.createAccessManagement }}
        - --create-release={{ .Values.controller.createRelease }}
        - --create-templates={{ .Values.controller.createTemplates }}
        - --validate-cluster-upgrade-path={{ .Values.controller.validateClusterUpgradePath }}
        - --enable-webhook={{ .Values.admissionWebhook.enabled | default false }}
        - --webhook-port={{ .Values.admissionWebhook.port }}
        - --webhook-cert-dir={{ .Values.admissionWebhook.certDir }}
        {{- range $key, $value := .Values.controller.logger }}
        {{- if not (eq (printf "%s" $value) "") }}
        - --zap-{{ $key }}={{ $value }}
        {{- end }}
        {{- end }}
        - --pprof-bind-address={{ .Values.controller.debug.pprofBindAddress }}
        {{- if .Values.controller.enableSveltosCtrl }}
        - --enable-sveltos-ctrl={{ .Values.controller.enableSveltosCtrl }}
        {{- end }}
        {{- if .Values.controller.enableSveltosExpiredCtrl }}
        - --enable-sveltos-expire-ctrl={{ .Values.controller.enableSveltosExpiredCtrl }}
        {{- end }}
        {{- if .Values.controller.defaultHelmTimeout }}
        - --default-helm-timeout={{ .Values.controller.defaultHelmTimeout }}
        {{- end }}
        - --max-concurrent-reconciles={{ .Values.controller.maxConcurrentReconciles }}
        command:
        - /manager
        env:
        - name: KCM_NAME
          value: {{ include "kcm.fullname" . }}-controller-manager
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.admissionWebhook.enabled }}
        ports:
        - containerPort: {{ .Values.admissionWebhook.port }}
          name: {{ include "kcm.webhook.portName" . }}
          protocol: TCP
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.resources | nindent 10 }}
        securityContext: {{ toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- if .Values.admissionWebhook.enabled }}
        volumeMounts:
          - mountPath: {{ .Values.admissionWebhook.certDir }}
            name: cert
            readOnly: true
        {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "kcm.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- if .Values.admissionWebhook.enabled }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "kcm.webhook.certName" . }}
      {{- end }}
