nameOverride: ""
fullnameOverride: ""

admissionWebhook:
  # enabled: false # WARN: setting the default value to false actually disables the WH; setting to true does not allow to install the KCM chart due to missing cert-manager CRDs
  port: 9443
  certDir: "/tmp/k8s-webhook-server/serving-certs/"

controller:
  templatesRepoURL: "oci://ghcr.io/k0rdent/kcm/charts"
  globalRegistry: ""
  globalK0sURL: ""
  k0sURLCertSecret: "" # @schema type: string; description: Name of a Secret containing K0s Download URL Root CA with ca.crt key
  registryCredsSecret: "" # @schema type: string; description: Name of a Secret containing Registry Credentials (Auth) Data
  registryCertSecret: "" # @schema type: string; description: Name of a Secret containing Registry Root CA with ca.crt key
  insecureRegistry: false
  createManagement: true
  createAccessManagement: true
  createRelease: true
  createTemplates: true
  nodeSelector: {} # @schema type: object; description: Node selector to constrain the pod to run on specific nodes
  affinity: {} # @schema type: object; description: Affinity rules for pod scheduling
  tolerations: [] # @schema type: array; description: Tolerations to allow the pod to schedule on tainted nodes
  validateClusterUpgradePath: true # @schema type: boolean; description: Specifies whether the ClusterDeployment upgrade path should be validated
  enableSveltosCtrl: true # @schema type: boolean; description: Enables built-in ServiceSet controller to reconcile ProjectSveltos objects
  enableSveltosExpiredCtrl: false # @schema type: boolean; description: Enables SveltosCluster controller, updating stuck (expired) sveltos management cluster kubeconfig tokens
  defaultHelmTimeout: "" # @schema type: string; description: Specifies the timeout duration for Helm install or upgrade operations. If unset, Fluxâ€™s default value will be used
  maxConcurrentReconciles: 10 # @schema type: integer; description: Specifies the maximum number of concurrent reconciles that will be run for each controller
  logger: # @schema title: Logger Settings; description: Global controllers logger settings; type: object
    devel: false # @schema type: boolean; description: Development defaults(encoder=console,logLevel=debug,stackTraceLevel=warn) Production defaults(encoder=json,logLevel=info,stackTraceLevel=error)
    encoder: "" # @schema enum:[json, console, ""] ; type: string
    log-level: "" # @schema enum:[info, debug, error, ""] ; type: string
    stacktrace-level: "" # @schema enum:[info, error, panic, ""] ; type: string
    time-encoding: rfc3339 # @schema enum:[epoch, millis, nano, iso8601, rfc3339, rfc3339nano, ""] ; type: string
  debug:
    pprofBindAddress: "" # @schema type: string; title: Set pprof binding address; description: The TCP address that the controller should bind to for serving pprof, '0' or empty value disables pprof; pattern: (?:^0?$)|(?:^(?:[\w.-]+(?:\.?[\w\.-]+)+)?:(?:[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$)

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

image:
  repository: ghcr.io/k0rdent/kcm/controller
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicas: 1

serviceAccount:
  annotations: {}

kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP

# Subcharts
flux2:
  enabled: true
  policies:
    create: false
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
  helmController:
    container:
      additionalArgs:
        - --watch-label-selector=k0rdent.mirantis.com/managed=true
  sourceController:
    container:
      additionalArgs:
        - --watch-label-selector=k0rdent.mirantis.com/managed=true

rbac-manager:
  enabled: true
