apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: azure-aks-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: azure-aks-0-2-0
  credential: azure-aks-credential
  propagateCredentials: false
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    location: "westus"
    machinePools:
      system:
        count: 1
        vmSize: Standard_A4_v2
      user:
        count: 1
        vmSize: Standard_A4_v2
