apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: azure-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: azure-standalone-cp-1-0-16
  credential: azure-cluster-identity-cred
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    controlPlaneNumber: 1
    workersNumber: 1
    location: "westus"
    subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
