apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: azure-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: azure-standalone-cp-0-2-0
  credential: azure-cluster-identity-cred
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    controlPlaneNumber: 1
    workersNumber: 1
    location: "westus"
    subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
    tenantID: "${AZURE_TENANT_ID}"
    clientID: "${AZURE_CLIENT_ID}"
    clientSecret: "${AZURE_CLIENT_SECRET}"
