apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: docker-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: docker-hosted-cp-0-2-0
  credential: docker-stub-credential
  config:
    clusterLabels: {}
    clusterAnnotations: {}
