apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: eks-${CLUSTER_NAME_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: aws-eks-0-2-0
  credential: "aws-cluster-identity-cred"
  config:
    clusterLabels: {}
    clusterAnnotations: {}
    region: ${AWS_REGION}
    workersNumber: 1
