apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-infra-kubeconfig
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
data:
  kubeconfig: ${KUBEVIRT_INFRA_KUBECONFIG_BASE64}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  name: kubevirt-cred
  namespace: ${NAMESPACE}
spec:
  identityRef:
    apiVersion: v1
    kind: Secret
    name: kubevirt-infra-kubeconfig
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-secret-resource-template
  namespace: ${NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: "kcm"
  annotations:
    projectsveltos.io/template: "true"
