name: Build latest binaries
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify all generated pieces are up-to-date
        run: make generate-all && git add -N . && git diff --exit-code
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version
        id: version
        run: |
          GIT_VERSION=$(git describe --tags --always)
          echo "version=${GIT_VERSION#v}" >> $GITHUB_OUTPUT
      - name: Build and push KCM controller image to the public repository
        uses: docker/build-push-action@v6
        with:
          build-args: |
            LD_FLAGS=-s -w -X github.com/K0rdent/kcm/internal/build.Version=${{ steps.version.outputs.version }}
          context: .
          platforms: linux/amd64
          tags: |
            ghcr.io/k0rdent/kcm/controller-ci:${{ steps.version.outputs.version }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Prepare and push KCM template charts to the public repository
        env:
          REGISTRY_REPO: oci://ghcr.io/k0rdent/kcm/charts-ci
          VERSION: ${{ steps.version.outputs.version }}
          IMG: ghcr.io/k0rdent/kcm/controller-ci:${{ steps.version.outputs.version }}
        run: |
          make set-kcm-repo
          make kcm-chart-release
          make helm-push