name: Issues and PRs Stale Cron
on:
  schedule:
    - cron: "0 10 * * *" # 10am UTC

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Stale non-active and remove marked with stale label
        uses: actions/stale@v10
        with:
          # issues
          days-before-issue-stale: 14
          days-before-issue-close: 14
          only-issue-labels: "needs-triage,question / discussion"
          exempt-issue-labels: "keep"
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open 14 days, labeled with needs-triage and question / discussion, and with no activity. Remove stale label or comment or this will be closed in 14 days."

          # pull requests
          days-before-pr-stale: 90
          days-before-pr-close: 30
          stale-pr-label: "stale"
          close-pr-label: "stale"
          exempt-pr-labels: "keep"
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
          stale-pr-message: "This PR is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days."
